package com.charlztech.tv.resources

object Strings {
    const val appName = "CharlzTechTV"
    const val navHome = "Home"
    const val navProviders = "Providers"
    const val navFavorites = "Favorites"
    const val navSearch = "Search"
    const val liveNow = "Live Now"
    const val upcoming = "Up Next"
    const val allProviders = "All Providers"
    const val servers = "Servers"
    const val previous = "Previous"
    const val next = "Next"
    const val retry = "Retry"
    const val noEvents = "No live events right now"
    const val noEventsFilterNamed = "No %s events right now"
    const val backToAllEvents = "Back to all events"
    const val noChannels = "No channels found"
    const val searchHint = "Search sports, teams, channels…"
    const val autoRefresh = "Auto-refreshing every 3 minutes"
    const val errorStream = "Unable to play stream"
    const val refresh = "Refresh"
    const val preparingStream = "Preparing stream…"
    const val bufferingLive = "Buffering live stream…"
    const val fullscreen = "Fullscreen"
    const val exitFullscreen = "Exit fullscreen"
    const val about = "About"
    const val aboutTitle = "About CharlzTechTV"
    const val aboutDeveloperLabel = "Developer"
    const val aboutDeveloperValue = "CharlzTech Software Developers (Charles Mabhande)"
    const val aboutPhoneLabel = "Phone"
    const val aboutPhoneValue = "+263776318768"
    const val aboutEmailLabel = "Email"
    const val aboutEmailValue = "charliemabhande@gmail.com"
    const val aboutTagline = "Live sports streaming for Windows"
    const val openInBrowser = "Open in browser"
    const val vlcRequired = "Install VLC Media Player (64-bit) to watch streams inside CharlzTechTV."
}
